name: stock_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  csv: ^5.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.8.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
